# Do NOT update manually; changes here will be overwritten by Copier
_commit: 28c9e52
_src_path: gh:Waalo-FenixERP/repository-template.git
dependency_installation_mode: OCA
generate_requirements_txt: false
include_wkhtmltopdf: true
odoo_version: 14.0
rebel_module_groups: []
repo_description: Open modules
repo_name: Open modules
repo_slug: open-modules
travis_apt_packages: []
travis_apt_sources: []
